### ISSUE TITLE
Successfully install data-explorer on dataverse, but the data-explore page keeps loading and show noting

### ISSUE THREAD

**Issue by ChenYi-qy** [scholarsportal/dataverse-data-explorer-v2#10]
[](url)I have followed the documentation's Github page part to integrate data-explore on dataverse, it does shows a 'data-expore' option on explore button, but when I click it, it takes me to a new page and shows nothing, anybody knows why?

This is how the page looks like:
![Screenshot from 2022-03-03 10-05-49](https://user-images.githubusercontent.com/58657543/156482799-8a0013bb-801c-4444-b92b-0588cc6ca697.png)

**Comment by kaitlinnewson** [comment]
Hi @ChenYi-qy, I've replied to your issue in the Dataverse google group: https://groups.google.com/g/dataverse-community/c/fvGvMQPnML0

**Comment by ChenYi-qy** [comment]
Thank you very much!!!
